version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - pytest
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r latest.zip .
      - aws s3 cp latest.zip s3://my-deploy-bucket/my-flask-app/latest.zip

artifacts:
  files:
    - '**/*'
